export const INITIAL_CLASSES = [
  { id: 'xi-to', name: 'XI TO' },
  { id: 'xi-tjkt-1', name: 'XI TJKT 1' },
  { id: 'xi-tjkt-2', name: 'XI TJKT 2' },
  { id: 'xi-mplb', name: 'XI MPLB' },
  { id: 'x-to', name: 'X TO' },
  { id: 'x-tjkt', name: 'X TJKT' },
  { id: 'x-mplb', name: 'X MPLB' },
];

export const INITIAL_STUDENTS: { name: string; classId: string; className: string }[] = [
  // XI TO
  { name: 'A. Rochman Djaelani', classId: 'xi-to', className: 'XI TO' },
  { name: 'Aerlangga Alfarizy', classId: 'xi-to', className: 'XI TO' },
  { name: 'Ananda Putra Nugraha', classId: 'xi-to', className: 'XI TO' },
  { name: 'Anaya Galang Saputra', classId: 'xi-to', className: 'XI TO' },
  { name: 'Fakhri Fauzan', classId: 'xi-to', className: 'XI TO' },
  { name: 'Fauzan Adam Juliana Putra', classId: 'xi-to', className: 'XI TO' },
  { name: 'Guruh Deandra Putra', classId: 'xi-to', className: 'XI TO' },
  { name: 'Hardiansyah', classId: 'xi-to', className: 'XI TO' },
  { name: 'Helmi Maulana', classId: 'xi-to', className: 'XI TO' },
  { name: 'Ilham Muhamad Ritazul Arifin', classId: 'xi-to', className: 'XI TO' },
  { name: 'Imam Jamasari', classId: 'xi-to', className: 'XI TO' },
  { name: 'Juandi Alrasyid', classId: 'xi-to', className: 'XI TO' },
  { name: 'M Bintang Pebriyansah', classId: 'xi-to', className: 'XI TO' },
  { name: 'M Fadhil Alfajri', classId: 'xi-to', className: 'XI TO' },
  { name: 'M Rehan Dika', classId: 'xi-to', className: 'XI TO' },
  { name: 'M Rezki Agustian', classId: 'xi-to', className: 'XI TO' },
  { name: 'M. Bintang Pratama', classId: 'xi-to', className: 'XI TO' },
  { name: 'M. Ramdan Herdiansyah', classId: 'xi-to', className: 'XI TO' },
  { name: 'M. Rifki Aditya', classId: 'xi-to', className: 'XI TO' },
  { name: 'Miftahul Fariz', classId: 'xi-to', className: 'XI TO' },
  { name: 'Moch Husni Mubarokh', classId: 'xi-to', className: 'XI TO' },
  { name: 'Muhammad Azka Maulana', classId: 'xi-to', className: 'XI TO' },
  { name: 'Muhamad Al Ghifari', classId: 'xi-to', className: 'XI TO' },
  { name: 'Muhamad Arya Wiratama', classId: 'xi-to', className: 'XI TO' },
  { name: 'Muhamad Nur Ihsan', classId: 'xi-to', className: 'XI TO' },
  { name: 'Muhammad Adrian', classId: 'xi-to', className: 'XI TO' },
  { name: 'Muhammad Alfiansyah', classId: 'xi-to', className: 'XI TO' },
  { name: 'Muhammad Azwan Al Buchori', classId: 'xi-to', className: 'XI TO' },
  { name: 'Muhammad Farhan Firdaus', classId: 'xi-to', className: 'XI TO' },
  { name: 'Muhammad Fauji', classId: 'xi-to', className: 'XI TO' },
  { name: 'Muhammad Siddiq Firmansyah', classId: 'xi-to', className: 'XI TO' },
  { name: 'Nendi Sanjaya', classId: 'xi-to', className: 'XI TO' },
  { name: 'Pirdan Maulana', classId: 'xi-to', className: 'XI TO' },
  { name: 'Rahman Mustopa', classId: 'xi-to', className: 'XI TO' },
  { name: 'Rifki Adriansyah', classId: 'xi-to', className: 'XI TO' },
  { name: 'Ripki Ramdani', classId: 'xi-to', className: 'XI TO' },
  { name: 'Rivansyah', classId: 'xi-to', className: 'XI TO' },
  { name: 'Riyan Hidayatuloh', classId: 'xi-to', className: 'XI TO' },
  { name: 'Rizki Fathani Aziz', classId: 'xi-to', className: 'XI TO' },
  { name: 'Rizky Abdurahman', classId: 'xi-to', className: 'XI TO' },
  { name: 'Satria Nurfirsatuloh', classId: 'xi-to', className: 'XI TO' },
  { name: 'Yadi Permana Sidik', classId: 'xi-to', className: 'XI TO' },
  { name: 'Zaki Muhamad Hanavi', classId: 'xi-to', className: 'XI TO' },
  { name: 'M Arya Ramadhan', classId: 'xi-to', className: 'XI TO' },
  // XI TJKT 1
  { name: 'Aang Maulana', classId: 'xi-tjkt-1', className: 'XI TJKT 1' },
  { name: 'Adit Maulana', classId: 'xi-tjkt-1', className: 'XI TJKT 1' },
  { name: 'Amir Rahman', classId: 'xi-tjkt-1', className: 'XI TJKT 1' },
  { name: 'Ananda Rizky Kukuh Adi Syahputra', classId: 'xi-tjkt-1', className: 'XI TJKT 1' },
  { name: 'Dimas Gustian', classId: 'xi-tjkt-1', className: 'XI TJKT 1' },
  { name: 'Dina Pratiwi', classId: 'xi-tjkt-1', className: 'XI TJKT 1' },
  { name: 'Fadli Iskandar', classId: 'xi-tjkt-1', className: 'XI TJKT 1' },
  { name: 'Heksa Muhammad Zacky', classId: 'xi-tjkt-1', className: 'XI TJKT 1' },
  { name: 'M Dika Permana', classId: 'xi-tjkt-1', className: 'XI TJKT 1' },
  { name: 'M. Nazwar Maulana Junaedi', classId: 'xi-tjkt-1', className: 'XI TJKT 1' },
  { name: 'Marlin Andini Hestiana', classId: 'xi-tjkt-1', className: 'XI TJKT 1' },
  { name: 'Mochamad Fauzi Rismanto', classId: 'xi-tjkt-1', className: 'XI TJKT 1' },
  { name: 'Mochammad Fhajar Syaputra', classId: 'xi-tjkt-1', className: 'XI TJKT 1' },
  { name: 'Muhamad Fakhri Azhuri', classId: 'xi-tjkt-1', className: 'XI TJKT 1' },
  { name: 'Muhamad Iman Rohman', classId: 'xi-tjkt-1', className: 'XI TJKT 1' },
  { name: 'Muhammad Fauzi Maulana', classId: 'xi-tjkt-1', className: 'XI TJKT 1' },
  { name: 'Muhammad Ilyas', classId: 'xi-tjkt-1', className: 'XI TJKT 1' },
  { name: 'Muhammad Rifki Ramadan', classId: 'xi-tjkt-1', className: 'XI TJKT 1' },
  { name: 'Muhammad Sopiyan', classId: 'xi-tjkt-1', className: 'XI TJKT 1' },
  { name: 'Raka Al Farizi', classId: 'xi-tjkt-1', className: 'XI TJKT 1' },
  { name: 'Randi Rustandi Rahman', classId: 'xi-tjkt-1', className: 'XI TJKT 1' },
  { name: 'Salma Prihartini', classId: 'xi-tjkt-1', className: 'XI TJKT 1' },
  { name: 'Salsa Safitri', classId: 'xi-tjkt-1', className: 'XI TJKT 1' },
  { name: 'Siti Nuraidah', classId: 'xi-tjkt-1', className: 'XI TJKT 1' },
  { name: 'Sulaeman', classId: 'xi-tjkt-1', className: 'XI TJKT 1' },
  { name: 'Suryadi', classId: 'xi-tjkt-1', className: 'XI TJKT 1' },
  { name: 'Hisam Fauzi', classId: 'xi-tjkt-1', className: 'XI TJKT 1' },
  { name: 'Muhammad Fauzi Zikram Muharam', classId: 'xi-tjkt-1', className: 'XI TJKT 1' },
  // XI TJKT 2
  { name: 'Agfi Abdul Salam', classId: 'xi-tjkt-2', className: 'XI TJKT 2' },
  { name: 'Ahmad Amirudin', classId: 'xi-tjkt-2', className: 'XI TJKT 2' },
  { name: 'Arip', classId: 'xi-tjkt-2', className: 'XI TJKT 2' },
  { name: 'Derisvan Irsandi', classId: 'xi-tjkt-2', className: 'XI TJKT 2' },
  { name: 'Fawaj Amanulloh', classId: 'xi-tjkt-2', className: 'XI TJKT 2' },
  { name: 'Hasna', classId: 'xi-tjkt-2', className: 'XI TJKT 2' },
  { name: 'Indra Setiawan', classId: 'xi-tjkt-2', className: 'XI TJKT 2' },
  { name: 'Lira Afriyanti', classId: 'xi-tjkt-2', className: 'XI TJKT 2' },
  { name: 'M Nasir Abdul Zabar', classId: 'xi-tjkt-2', className: 'XI TJKT 2' },
  { name: 'M. Zam Zam Saerul Lana', classId: 'xi-tjkt-2', className: 'XI TJKT 2' },
  { name: 'M.Raihan Apriliyan', classId: 'xi-tjkt-2', className: 'XI TJKT 2' },
  { name: 'Moh Luky Kurniawan', classId: 'xi-tjkt-2', className: 'XI TJKT 2' },
  { name: 'Muhamad Ramdani', classId: 'xi-tjkt-2', className: 'XI TJKT 2' },
  { name: 'Muhamad Rizky Setiawan', classId: 'xi-tjkt-2', className: 'XI TJKT 2' },
  { name: 'Muhammad Maulana Yusup Hermawan', classId: 'xi-tjkt-2', className: 'XI TJKT 2' },
  { name: 'Muhammad Yusup', classId: 'xi-tjkt-2', className: 'XI TJKT 2' },
  { name: 'Nuri Syafiina', classId: 'xi-tjkt-2', className: 'XI TJKT 2' },
  { name: 'Nurika Maya Agustina', classId: 'xi-tjkt-2', className: 'XI TJKT 2' },
  { name: 'Raka Yudistira Azhar', classId: 'xi-tjkt-2', className: 'XI TJKT 2' },
  { name: 'Rin Rin Maspuroh', classId: 'xi-tjkt-2', className: 'XI TJKT 2' },
  { name: 'Silfia Siti Salsa', classId: 'xi-tjkt-2', className: 'XI TJKT 2' },
  { name: 'Siti Fitriani', classId: 'xi-tjkt-2', className: 'XI TJKT 2' },
  { name: 'Wildan Nur Ilyasa', classId: 'xi-tjkt-2', className: 'XI TJKT 2' },
  { name: 'Muhammad Rizki Fadilah', classId: 'xi-tjkt-2', className: 'XI TJKT 2' },
  { name: 'Muhamad Rifaldi Saputra', classId: 'xi-tjkt-2', className: 'XI TJKT 2' },
  { name: 'Muhammad Abdul Kodir Jaelani', classId: 'xi-tjkt-2', className: 'XI TJKT 2' },
  { name: 'Salma Nurkholizah', classId: 'xi-tjkt-2', className: 'XI TJKT 2' },
  { name: 'Muhammad Raihan', classId: 'xi-tjkt-2', className: 'XI TJKT 2' },
  { name: 'Memey Santika Lestari', classId: 'xi-tjkt-2', className: 'XI TJKT 2' },
  // XI MPLB
  { name: 'Ajela Fitria Julva', classId: 'xi-mplb', className: 'XI MPLB' },
  { name: 'Amalia Hasna', classId: 'xi-mplb', className: 'XI MPLB' },
  { name: 'Anisa Septiani Fitri', classId: 'xi-mplb', className: 'XI MPLB' },
  { name: 'Annisa Fauziah', classId: 'xi-mplb', className: 'XI MPLB' },
  { name: 'Annisa Nur Maulidia', classId: 'xi-mplb', className: 'XI MPLB' },
  { name: 'Defyta Sri Haryani', classId: 'xi-mplb', className: 'XI MPLB' },
  { name: 'Destri Herdiawati', classId: 'xi-mplb', className: 'XI MPLB' },
  { name: 'Gita Siti Fadilah', classId: 'xi-mplb', className: 'XI MPLB' },
  { name: 'Lesti Lianita', classId: 'xi-mplb', className: 'XI MPLB' },
  { name: 'Lusi Sulistiawati', classId: 'xi-mplb', className: 'XI MPLB' },
  { name: 'Mutia Nurlita', classId: 'xi-mplb', className: 'XI MPLB' },
  { name: 'Nadia Febriani', classId: 'xi-mplb', className: 'XI MPLB' },
  { name: "Najwa Syahrul Ma'Wa", classId: 'xi-mplb', className: 'XI MPLB' },
  { name: 'Nanah Ramdanah', classId: 'xi-mplb', className: 'XI MPLB' },
  { name: 'Nayla Septiani Kristiawan', classId: 'xi-mplb', className: 'XI MPLB' },
  { name: 'Nisrina Hanizias', classId: 'xi-mplb', className: 'XI MPLB' },
  { name: 'Nurul Patimah', classId: 'xi-mplb', className: 'XI MPLB' },
  { name: 'Rahma Maulida', classId: 'xi-mplb', className: 'XI MPLB' },
  { name: 'Ratna Seza', classId: 'xi-mplb', className: 'XI MPLB' },
  { name: 'Resti Septi Ramadani', classId: 'xi-mplb', className: 'XI MPLB' },
  { name: 'Saika Moza Aulia', classId: 'xi-mplb', className: 'XI MPLB' },
  { name: 'Salsyah Nuraeni Tri Rizki', classId: 'xi-mplb', className: 'XI MPLB' },
  { name: 'Saripah Oktapiyani', classId: 'xi-mplb', className: 'XI MPLB' },
  { name: 'Selomita Azahra Hoirunnisa', classId: 'xi-mplb', className: 'XI MPLB' },
  { name: 'Sherly Yulianti Safitri', classId: 'xi-mplb', className: 'XI MPLB' },
  { name: 'Siti Amelia', classId: 'xi-mplb', className: 'XI MPLB' },
  { name: 'Siti Ane Ayunindia', classId: 'xi-mplb', className: 'XI MPLB' },
  { name: 'Siti Azkia Adawiah', classId: 'xi-mplb', className: 'XI MPLB' },
  { name: 'Siti Nurfitriyani Azzahra', classId: 'xi-mplb', className: 'XI MPLB' },
  { name: 'Siti Rahmawati', classId: 'xi-mplb', className: 'XI MPLB' },
  { name: "Siti Rubai'ah Adawiyah", classId: 'xi-mplb', className: 'XI MPLB' },
  { name: 'Siti Salwa', classId: 'xi-mplb', className: 'XI MPLB' },
  { name: 'Siti Sopiah', classId: 'xi-mplb', className: 'XI MPLB' },
  { name: 'Tiara Novi Yanti', classId: 'xi-mplb', className: 'XI MPLB' },
  { name: 'Tri Safitri', classId: 'xi-mplb', className: 'XI MPLB' },
  { name: 'Vhannesya Nayya Parsaulian Sitompul', classId: 'xi-mplb', className: 'XI MPLB' },
  { name: 'Yusri Billah Azzahra', classId: 'xi-mplb', className: 'XI MPLB' },
  { name: 'Riska Amelia Hernayanti', classId: 'xi-mplb', className: 'XI MPLB' },
  { name: 'Maya Siti Agustiani', classId: 'xi-mplb', className: 'XI MPLB' },
  { name: 'Marisa Putri Soraya', classId: 'xi-mplb', className: 'XI MPLB' },
  // X TO
  { name: 'Afriana', classId: 'x-to', className: 'X TO' },
  { name: 'Ahmad Nopal', classId: 'x-to', className: 'X TO' },
  { name: 'Arya Ramadhan', classId: 'x-to', className: 'X TO' },
  { name: 'Beny Satria Putra', classId: 'x-to', className: 'X TO' },
  { name: 'Devano Nandika', classId: 'x-to', className: 'X TO' },
  { name: 'Hadi Maulana', classId: 'x-to', className: 'X TO' },
  { name: 'Irwansyah', classId: 'x-to', className: 'X TO' },
  { name: 'M Fahri Prasetya', classId: 'x-to', className: 'X TO' },
  { name: 'M. Irpan Abdurohman', classId: 'x-to', className: 'X TO' },
  { name: 'M Rapa Ibrahim', classId: 'x-to', className: 'X TO' },
  { name: 'M Wildan Humaezi', classId: 'x-to', className: 'X TO' },
  { name: 'Maulana', classId: 'x-to', className: 'X TO' },
  { name: 'Moch Bagus Tri Ramadhan', classId: 'x-to', className: 'X TO' },
  { name: 'Moh Aldi Febrian', classId: 'x-to', className: 'X TO' },
  { name: 'Muhamad Sandika', classId: 'x-to', className: 'X TO' },
  { name: 'Muhamad Arfan Hawari', classId: 'x-to', className: 'X TO' },
  { name: 'Muhamad Helmi Palyani', classId: 'x-to', className: 'X TO' },
  { name: 'Muhamad Putra Aryagung', classId: 'x-to', className: 'X TO' },
  { name: 'Muhamad Saepul Hidayat', classId: 'x-to', className: 'X TO' },
  { name: "Muhammad Ali Sa'Ban", classId: 'x-to', className: 'X TO' },
  { name: 'Muhammad Fajar Al-Farizi', classId: 'x-to', className: 'X TO' },
  { name: 'Muhammad Lutfi Hadi Pratama', classId: 'x-to', className: 'X TO' },
  { name: 'Muhammad Raihan Dwi Saputra', classId: 'x-to', className: 'X TO' },
  { name: 'Muhammad Rizki Fauzi', classId: 'x-to', className: 'X TO' },
  { name: 'Muhammad Rizki Pratama', classId: 'x-to', className: 'X TO' },
  { name: 'Muhammad Zhidan Maulid Ramdani', classId: 'x-to', className: 'X TO' },
  { name: 'Radhi Riyadi', classId: 'x-to', className: 'X TO' },
  { name: 'Raditya Avrizal', classId: 'x-to', className: 'X TO' },
  { name: 'Raditya Firmansyah', classId: 'x-to', className: 'X TO' },
  { name: 'Rahmat', classId: 'x-to', className: 'X TO' },
  { name: 'Rifky Zatmika', classId: 'x-to', className: 'X TO' },
  { name: 'Sani Kurniawan', classId: 'x-to', className: 'X TO' },
  { name: 'Yuri Rahmat Saleh', classId: 'x-to', className: 'X TO' },
  { name: 'Muhamad Abdul Pahdi', classId: 'x-to', className: 'X TO' },
  // X TJKT
  { name: 'Alif Muhamad Al Zikri', classId: 'x-tjkt', className: 'X TJKT' },
  { name: 'Alip Abdul Patah', classId: 'x-tjkt', className: 'X TJKT' },
  { name: 'Angga Maulana Kusumah', classId: 'x-tjkt', className: 'X TJKT' },
  { name: 'Anisa Sri Aulia', classId: 'x-tjkt', className: 'X TJKT' },
  { name: 'Ayudia Irawan', classId: 'x-tjkt', className: 'X TJKT' },
  { name: 'Cep Isya Ansori', classId: 'x-tjkt', className: 'X TJKT' },
  { name: 'Cep Salman Aziz', classId: 'x-tjkt', className: 'X TJKT' },
  { name: 'Derin Regina Astuti', classId: 'x-tjkt', className: 'X TJKT' },
  { name: 'Desti Fitri Septiani', classId: 'x-tjkt', className: 'X TJKT' },
  { name: 'Deva Haidar Rafif Haryadi', classId: 'x-tjkt', className: 'X TJKT' },
  { name: 'Dina Inayah', classId: 'x-tjkt', className: 'X TJKT' },
  { name: 'Fajar', classId: 'x-tjkt', className: 'X TJKT' },
  { name: 'Firda Ferdianti', classId: 'x-tjkt', className: 'X TJKT' },
  { name: 'Firman Abdul Majid', classId: 'x-tjkt', className: 'X TJKT' },
  { name: 'Hendi Juandi', classId: 'x-tjkt', className: 'X TJKT' },
  { name: 'M Rokib Alamsyah', classId: 'x-tjkt', className: 'X TJKT' },
  { name: 'M. Angga Rusmana', classId: 'x-tjkt', className: 'X TJKT' },
  { name: 'Moch Fahri Idris', classId: 'x-tjkt', className: 'X TJKT' },
  { name: 'Moch. Firmansah', classId: 'x-tjkt', className: 'X TJKT' },
  { name: "Mochamad Daffa Al Faa'Iz Setiawan", classId: 'x-tjkt', className: 'X TJKT' },
  { name: 'Muhamad Azkiya Azis', classId: 'x-tjkt', className: 'X TJKT' },
  { name: 'Muhammad Habibi Arsya Agniya', classId: 'x-tjkt', className: 'X TJKT' },
  { name: 'Muhammad Irgi Farid', classId: 'x-tjkt', className: 'X TJKT' },
  { name: 'Muhammad Nabil Al Haqqi', classId: 'x-tjkt', className: 'X TJKT' },
  { name: 'Muhammad Razib Al Rahmat', classId: 'x-tjkt', className: 'X TJKT' },
  { name: 'Muhammad Yahya Wijaya', classId: 'x-tjkt', className: 'X TJKT' },
  { name: 'Nadila Rahma Aulia', classId: 'x-tjkt', className: 'X TJKT' },
  { name: 'Nayla Ramziah', classId: 'x-tjkt', className: 'X TJKT' },
  { name: 'Neng Jahra Fusfita', classId: 'x-tjkt', className: 'X TJKT' },
  { name: 'Qirani Nur Friza', classId: 'x-tjkt', className: 'X TJKT' },
  { name: 'Raisa Maulana Firmansyah', classId: 'x-tjkt', className: 'X TJKT' },
  { name: 'Reza Pratama', classId: 'x-tjkt', className: 'X TJKT' },
  { name: 'Rifat Nur Alamsyah', classId: 'x-tjkt', className: 'X TJKT' },
  { name: 'Rizki Maulana', classId: 'x-tjkt', className: 'X TJKT' },
  { name: 'Silvia Nurul Isnaini', classId: 'x-tjkt', className: 'X TJKT' },
  { name: 'Siti Choerunisa Pertiwi', classId: 'x-tjkt', className: 'X TJKT' },
  { name: 'Siti Salsabila Mulyasari', classId: 'x-tjkt', className: 'X TJKT' },
  { name: 'Siti Yaspi Sopi Mariyah', classId: 'x-tjkt', className: 'X TJKT' },
  { name: 'Syamsul Munawar', classId: 'x-tjkt', className: 'X TJKT' },
  { name: 'Vania Febriani', classId: 'x-tjkt', className: 'X TJKT' },
  { name: 'Zulfan Azhar Maulana', classId: 'x-tjkt', className: 'X TJKT' },
  { name: 'Aiman Afdhal Nauf', classId: 'x-tjkt', className: 'X TJKT' },
  // X MPLB
  { name: 'Ajeng Airil Azmi', classId: 'x-mplb', className: 'X MPLB' },
  { name: 'Alya Alfadiyah', classId: 'x-mplb', className: 'X MPLB' },
  { name: 'Asha Syauqi Bintang Maulida', classId: 'x-mplb', className: 'X MPLB' },
  { name: 'Asya Siti Pedana', classId: 'x-mplb', className: 'X MPLB' },
  { name: 'Aulia Putri', classId: 'x-mplb', className: 'X MPLB' },
  { name: 'Citra Nurahmah', classId: 'x-mplb', className: 'X MPLB' },
  { name: 'Dini Balqis Faiha', classId: 'x-mplb', className: 'X MPLB' },
  { name: 'Elsa Cahyati', classId: 'x-mplb', className: 'X MPLB' },
  { name: 'Erina Fauziah', classId: 'x-mplb', className: 'X MPLB' },
  { name: 'Fitri Salsabila', classId: 'x-mplb', className: 'X MPLB' },
  { name: 'Gina Agustina', classId: 'x-mplb', className: 'X MPLB' },
  { name: 'Hasniah Adrikni', classId: 'x-mplb', className: 'X MPLB' },
  { name: 'Herawati Puspitasari', classId: 'x-mplb', className: 'X MPLB' },
  { name: 'Keysha Nuralifa', classId: 'x-mplb', className: 'X MPLB' },
  { name: 'Meilinda Siti Maspupah', classId: 'x-mplb', className: 'X MPLB' },
  { name: 'Nabila Nurul Anbiya', classId: 'x-mplb', className: 'X MPLB' },
  { name: 'Nadya Fitria Yulianti', classId: 'x-mplb', className: 'X MPLB' },
  { name: 'Neng Elsa Safitri', classId: 'x-mplb', className: 'X MPLB' },
  { name: 'Neng Rajma Erlianti', classId: 'x-mplb', className: 'X MPLB' },
  { name: 'Neng Salma Seftiyani', classId: 'x-mplb', className: 'X MPLB' },
  { name: 'Neyra Putri Friandis', classId: 'x-mplb', className: 'X MPLB' },
  { name: 'Nova Novita', classId: 'x-mplb', className: 'X MPLB' },
  { name: 'Putri Regina', classId: 'x-mplb', className: 'X MPLB' },
  { name: 'Rastianika Putri Marlina', classId: 'x-mplb', className: 'X MPLB' },
  { name: 'Reni Nur Anggraeni', classId: 'x-mplb', className: 'X MPLB' },
  { name: 'Renita Apriliyani', classId: 'x-mplb', className: 'X MPLB' },
  { name: 'Reva Novianti', classId: 'x-mplb', className: 'X MPLB' },
  { name: 'Revia Laelatus Syafariah', classId: 'x-mplb', className: 'X MPLB' },
  { name: 'Rismawanti', classId: 'x-mplb', className: 'X MPLB' },
  { name: 'Riyanti Novala Sari', classId: 'x-mplb', className: 'X MPLB' },
  { name: 'Sarah Muzdalipah', classId: 'x-mplb', className: 'X MPLB' },
  { name: 'Sela Amalia', classId: 'x-mplb', className: 'X MPLB' },
  { name: 'Silvia Septiana', classId: 'x-mplb', className: 'X MPLB' },
  { name: 'Siti Anisa', classId: 'x-mplb', className: 'X MPLB' },
  { name: 'Siti Aurora Risda Handayani', classId: 'x-mplb', className: 'X MPLB' },
  { name: 'Siti Azka Fauziah Suhendar', classId: 'x-mplb', className: 'X MPLB' },
  { name: 'Siti Nuraeni', classId: 'x-mplb', className: 'X MPLB' },
  { name: "Siti Siva'u Rahmah", classId: 'x-mplb', className: 'X MPLB' },
  { name: 'Syifa Mulyani', classId: 'x-mplb', className: 'X MPLB' },
  { name: 'Vira Sasmita Handriyani', classId: 'x-mplb', className: 'X MPLB' },
  { name: 'Zazma', classId: 'x-mplb', className: 'X MPLB' },
  { name: 'Pani Hardianti', classId: 'x-mplb', className: 'X MPLB' },
  { name: 'Zulfia Zahra', classId: 'x-mplb', className: 'X MPLB' },
  { name: 'Natasya Azizah Johan', classId: 'x-mplb', className: 'X MPLB' },
  { name: 'Keyla Noer Febryanti', classId: 'x-mplb', className: 'X MPLB' },
  { name: 'Azhar Pratami Ramadina', classId: 'x-mplb', className: 'X MPLB' },
];
